# Generated by Django 3.2.9 on 2021-11-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
